services:
  - type: web
    name: kenics-backend
    runtime: node
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
